#!/bin/sh
set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ]; then
  useradd nodekeeper -r || echo "User already exists."
  path="/var/nodekeeper"

  mkdir -p $path

  chown nodekeeper:nodekeeper -R $path
  chmod 770 -R $path
  chmod g+s -R $path
fi
#DEBHELPER#
