#!/bin/sh
set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ]; then
  useradd stever -r
  path="/var/stever"
  (mkdir -p $path && chown stever:stever -R $path) || true
fi
#DEBHELPER#
